# Generated by Django 4.1.5 on 2023-01-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment_amount_payment_status_payment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
